### ISSUE TITLE
disqus not loading

### ISSUE THREAD

**Issue by Dasonk** [useR-2018/website#1]
It seems like disqus isn't loading properly and gives "We were unable to load Disqus. If you are a moderator please see our troubleshooting guide."

My best guess is that [trusted domains](https://help.disqus.com/customer/portal/articles/1261429) aren't set up properly but I can't verify that.

**Comment by dicook** [comment]
thx - was planning on removing the disqus. You are quick - just trying out
web designs!

On Apr 18, 2017, at 12:18 AM, Dason Kurkiewicz <notifications@github.com>
wrote:

It seems like disqus isn't loading properly and gives "We were unable to
load Disqus. If you are a moderator please see our troubleshooting guide."

My best guess is that trusted domains aren't set up properly but I can't
verify that.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


On Tue, Apr 18, 2017 at 12:18 AM, Dason Kurkiewicz <notifications@github.com
